DOMAIN = "tarti"
NAME = "BLE Tartı"
MANUFACTURER = "Tartı"
MODEL = "BLE Tartı"

CONF_SCALE_ADDRESS = "scale_address"
CONF_PERSONS = "persons"
CONF_PERSON_NAME = "name"

MIN_VALID_WEIGHT = 3.0
STABILITY_READINGS = 3
STABILITY_TOLERANCE = 0.3
EMPTY_TIMEOUT = 30

EVENT_PENDING = "tarti_measurement_pending"
SERVICE_ASSIGN = "assign"

ATTR_PERSON = "person"
ATTR_WEIGHT = "weight"